# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idx < Formula
  desc "Fast local file indexer and search tool"
  homepage "https://github.com/eltu/idx"
  version "0.7.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-darwin-amd64.tar.gz"
      sha256 "9e26e42dfa46af788a76378509338c3eb39d0cbc184cf43159ad32b1cf780229"

      define_method(:install) do
        bin.install "idx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-darwin-arm64.tar.gz"
      sha256 "5c75b5a53fd9ed87cf8e0c0bf5b1adeafb1cdb7e67dac06388caca2570e23a36"

      define_method(:install) do
        bin.install "idx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-linux-amd64.tar.gz"
      sha256 "6ceb96cce72d4e9e512749418e34a7137af761661c645dcd5602121b7bf03463"
      define_method(:install) do
        bin.install "idx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-linux-arm64.tar.gz"
      sha256 "ea06532958146de978760ef79c64b7941d8b90c96124874e54806069065472b5"
      define_method(:install) do
        bin.install "idx"
      end
    end
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
