# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idx < Formula
  desc "Fast local file indexer and search tool"
  homepage "https://github.com/eltu/idx"
  version "0.7.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-darwin-amd64.tar.gz"
      sha256 "6097e72796e8c5ae2435d11136626f3b623c99fa9054efe5d3bcb7e031e78bb5"

      define_method(:install) do
        bin.install "idx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-darwin-arm64.tar.gz"
      sha256 "01aeb1c6a01cfc71f670fcb5db400b719dfd9a5143c6933633ddc4eec01d5140"

      define_method(:install) do
        bin.install "idx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-linux-amd64.tar.gz"
      sha256 "97d390c9b240e588cf07408ec7fb2dd048ee2d6855c3a9b21db02702bdd90619"
      define_method(:install) do
        bin.install "idx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eltu/idx/releases/download/v0.7.0/idx-0.7.0-linux-arm64.tar.gz"
      sha256 "c78e85d7e1cb99f65fee8869e02176931c6a80e6d3d18b12f8bb2c99657ec54a"
      define_method(:install) do
        bin.install "idx"
      end
    end
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
